### ISSUE TITLE
Loading AIFFs works sporadically

### ISSUE THREAD

**Issue by unilock** [puddletag/puddletag#645] opened 2021-11-05 21:55 UTC
I'm having some issues loading AIFF files.

Loading AIFF files by dragging+dropping into the puddletag window does not work. No output on the command line, and nothing changes in the window.

Loading AIFF files using "Open Folder works fine, but results in the below traceback (the folder still opens in puddletag, and the GUI shows no errors).

`lsb_release -a`:
```
Distributor ID: Pop
Description:    Pop!_OS 21.04
Release:    21.04
Codename:   hirsute
```

puddletag info:
```
puddletag Version: 2.0.1
Locale: en_US
```

Loading a folder with multiple AIFFs using "Open Folder":
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/puddlestuff/mainwin/storedtags.py", line 116, in _load
    vlabel = QLabel(value)
TypeError: arguments did not match any overloaded call:
  QLabel(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'bytes'
  QLabel(str, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'bytes'
```

This issue goes along with my other issue at #646.

Let me know what you think.

EDIT: Loading AIFFs via drag+drop works *sometimes,* like immediately after opening puddletag. Selecting the AIFF afterwards results in the above traceback.

**Comment by corubba** [comment] 2022-02-10 22:30
AIFF files use ID3, so they shouldn't be any different than MP3 files. In fact I can open AIFF files just fine on my system and on PopOS in a virtual machine. I can however reproduce the error when loading a AIFF file which contains a UFID ID3 frame, so this seems to be the same issue as #565. Can you please check that, and maybe even see if you still have that issue with the latest version in the `master` branch?

**Comment by sandrotosi** [comment] 2022-02-11 03:06
fixed via #693 (if not, please reopen, thanks!)

**Comment by unilock** [comment] 2022-02-11 13:06
@corubba According to `ffprobe`, the AIFF files I'm testing do NOT contain UFID frames. I've uploaded one such file here:
https://mega.nz/file/RpMFnKSa#RjEqtYpFGwCC9-Fc8gzfhzcrw4MbG6MlR1Y_rBJQSLA

**Comment by corubba** [comment] 2022-02-11 21:36
I'm afraid I have to disagree, that file contains a UFID frame as can be seen with e.g. a hex editor.
![puddletag_645_hex](https://user-images.githubusercontent.com/97832352/153672346-435e09e9-545b-4a21-a760-64bd117b6ab4.png)

I was also able to open that file without any problems or crashes using the latest `master` branch. The identifier itself is 0 bytes (which is valid and within spec), puddletag shows this as an empty string. I will thus close the issue (again).
![puddletag_645](https://user-images.githubusercontent.com/97832352/153672524-acc40b58-a0b6-4541-9c51-aa6aa1c77866.png)

As a side note: The UFID owner identifier is "invalid", it should contain a URL. Aside from that, it also contains some weird characters at the start, the same as the URLs further down.

**Closed by corubba** 2022-02-11 21:36 UTC
Labels: new-file-support
