### ISSUE TITLE
No Actions

### ISSUE THREAD

**Issue by sandrotosi** [puddletag/puddletag#510] opened 2020-08-22 22:55 UTC
<a href="https://github.com/Pastim"><img src="https://avatars0.githubusercontent.com/u/1884726?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Pastim](https://github.com/Pastim)**
_Tue Jun 16 15:48:05 2020_
_Originally opened as https://github.com/sandrotosi/puddletag/issues/31_

----

I just tried this on ubuntu 20.04.

I see no Actions at all when I select that menu item.

I'll revert to the appimage version for now.

**Comment by Pastim** [comment] 2020-10-26 12:31
I had forgotten that I'd raised this on a pre-release version of the qt5 I'll close this case and leave #549 open..

**Comment by Pastim** [comment] 2020-10-26 12:52
First, I just ran the new 2.0.1 version.  I have a track on display.  I select Actions from the menu and see the list of 4 sub-menu items.  When I select Actions I see none at all.

So I renamed .config/puddletag and restarted puddletag.  This is a bit of an issue for me since I have a load of configuration items, including loads of new tags, changed tag panel, changed list of genres, and so on. 

This time (unlike on the pre-release), I can see the Actions list. A simple action does work. 

However, when I run my main Action macro to finalise all the tags on a track, it does nothing.   When I select Actions again, the list of Actions has disappeared.  If I stop and restart puddletag I still see no list of Actions.

Looking at the syslog I see the log below.  It looks as if some standard function is not compatible with python3.

Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]: Traceback (most recent call last):
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/mainwin/funcs.py", line 401, in run_action
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     win = actiondlg.ActionWindow(parent, example)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/actiondlg.py", line 778, in __init__
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     self.updateExample()
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/actiondlg.py", line 932, in updateExample
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     tags = apply_macros(macros, self.example, state,
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 655, in apply_macros
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     return apply_actions(actions, audio, state)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 620, in apply_actions
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     temp = func.runFunction(val, audio, state, None, r_tags)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 870, in runFunction
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     return func(**topass)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/functions.py", line 212, in formatValue
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     ret = findfunc.parsefunc(p_pattern, m_tags, state=state)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 440, in parsefunc
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     func_parsed, offset = parsefunc(s[i:], m_audio, s_audio, state, extra, True)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 462, in parsefunc
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     func_parsed = run_format_func(func[0], func[1:], m_audio, s_audio, state=state, extra=extra)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 328, in run_format_func
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     message = message.arg(arglen_error(e, topass, func, False))
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 67, in arglen_error
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     raise e
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/findfunc.py", line 322, in run_format_func
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     ret = func(**topass)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/functions.py", line 778, in to_ascii
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     return ''.join(c for c in cleaned_fn if c in VALID_FILENAME_CHARS)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:   File "/home/crusty/Programs/puddletag/source/puddlestuff/functions.py", line 778, in <genexpr>
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]:     return ''.join(c for c in cleaned_fn if c in VALID_FILENAME_CHARS)
Oct 26 12:48:55 TimPassingham puddletag.desktop[17319]: TypeError: 'in <string>' requires string as left operand, not int
Oct 26 12:48:58 TimPassingham puddletag.desktop[17319]: puddletag Version: 2.0.1, Changeset: 2ee6139ce75fcac959968143023ce0b9d1d2e13f
Oct 26 12:48:58 TimPassingham puddletag.desktop[17319]: Locale: en_GB



Next, when I select Actions again on the menu I don't see any Actions at all, just like at the start.

**Comment by blueblots** [comment] 2020-10-26 14:20
Can you share the macro and any other relevant configuration that is
triggering this, so I can try to reproduce the issue on my end. I can't
get the error right now (with my configuration) so its hard for me to
test any fixes.

**Comment by Pastim** [comment] 2020-10-26 16:27
Here's the macro.  I believe the issue is line 778 in functions.py, in the "to_ascii" function.  The 'in' operand may have changed syntax between python 2 and 3.


[Finish.zip](https://github.com/puddletag/puddletag/files/5440042/Finish.zip)

**Comment by blueblots** [comment] 2020-10-27 10:54
Hey can you inform me on how to load the action? I've placed it in both
the .config/puddletag folder and source/puddlestuff/data, but its not
showing up.

My apologies, I haven't loaded a custom action like this into puddletag
before.

**Comment by Pastim** [comment] 2020-10-27 12:43
Hi,

Rather than try to create the whole of my slightly complicated macro, I suggest you create a new action, such as:

Format artistsort using $upper($to_ascii($meta_sep(artist,/))) 

ie: function - Format value, fields - artistsort, format string - $upper($to_ascii($meta_sep(artist,/))) )

This creates a new tag, artistsort, from one or more artist tags (it's not the complete macro for create a sort form of artist, but it's the part that fails).

This causes the problems I have.  If I remove the $to_ascii function from it all seems OK (so far).  I need that function to create sort forms without complex european character sets.

**Comment by Pastim** [comment] 2020-10-28 10:11
I can now confirm that the new version is fine (and can keep my original .config/puddletag setup) except for the $to_ascii function.  Having removed it for now everything is good.  Thanks.

It's a mere 2 lines, but clearly doesn't work in python 3, as shown in the syslog extract I posted earlier.  I'm pretty ignorant about python.  Can someone help to sort it out?  It's a very useful function.

**Comment by Pastim** [comment] 2020-10-29 12:57
Hi 

I have the solution to the code problem that I had.  In functions.py, the to_ascii function needs a very small change to make it compatible with python 3.

The last line of to_ascii (line 778 in my copy of functions.py)  should now read:

    return ''.join(chr(c) for c in cleaned_fn if chr(c) in VALID_FILENAME_CHARS)

All that's changed is to make sure the two 'c' items are characters, i.e. chr(c).

The internet is a wonderful thing - sometimes!  I searched for the original line, and found it in https://stackoverflow.com/questions/295135/turn-a-string-into-a-valid-filename 
The solution was also in there further down.

My system is now up, running and stable.  Thanks again to the effort that has been in to doing this.

Can someone put this fix into the python 3 version here?  I've no idea how to do that, or what the protocol is.

**Comment by blueblots** [comment] 2020-10-29 16:04
That's good to hear, if you've got it working then you can open a pull
request on the main repository (puddletag/puddletag) and get your
changes merged. There's no protocol beyond getting something to work :)

**Comment by Pastim** [comment] 2020-10-29 20:30
blueblots - I'm afraid that's way above my pay grade. It looks to be a really complicated public process.  I'm very slow at new stuff, in programming languages I don't even understand, and I struggle with the modern way of making and applying patches.  I can fix my own code, by trial and error, but making changes to public software is a whole different ballgame.

If someone else is prepared to try the fix I suggested, I'd be happy to comment, pull a version and retest it,  and so on.

Sorry to be such a wimp.  As you may have gathered I'm not as young as I was.  Once upon a time I might have had a go, preferably in 360 assembler, TAL, or Fortran II, but I'm not quite as young as I was, and I've never, ever, dared to make any changes on github or similar.   Open software is still something of a wonderful mystery to me.

**Comment by blueblots** [comment] 2020-10-30 11:21
Hi pastim, having copied the action you sent into puddletag I was able
to replicate a crash, in fact I couldn't even get to the Action dialog
without a crash with the `$to_ascii` function in the actions; with your
fix the crashes are gone, I can run the action with no crash and set
the `artistsort` tag.

Although I can't view the tag within puddletag, I can see it in other
applications such as kid3. Is this a problem you've experienced or am I
missing some configuration?

Anyhow if its working for you, I can submit the change today/tomorrow
if you're ok with that.

**Comment by Pastim** [comment] 2020-10-30 12:41
That would be fine with me.  Thanks very much indeed.

To see different tags you can right click on a track that has had the action run on it and selected Extended Tags.  Or to see it on all tracks you can right click on the row on tag names across the top of the page, Select Columns, add artistsort as the tag name and field in the two fields on the right, and select the + icon.

**Closed** 2020-10-31 18:45 UTC
Labels: py3k-port
