### ISSUE TITLE
Loading 

### ISSUE THREAD

**Issue by audiomuze** [puddletag/puddletag#657] opened 2021-12-23 16:53 UTC
I'm seeing this most times I fire up puddletag:

```
puddletag Version: 2.0.1, Changeset: e5fb85c34ff2e699ca35274298d1921f2598be98
Locale: en_GB
Traceback (most recent call last):
  File "/home/x/git/puddletag/source/puddlestuff/tagmodel.py", line 2483, in wheelEvent
    h.setValue(h.value() - numsteps)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by sandrotosi** [comment] 2021-12-25 06:32
I'm afraid we need more information that this terse message:

- what distro do you use
- have you recently update?
- if not, please update your repository packages
- if yes, which packages were recently updated that may have impacted puddeltag functionalities (you can check the first-level dependencies in the README)

**Comment by audiomuze** [comment] 2021-12-28 14:28
Arch Linux: 5.15.11-arch2-1
Using Qt version 5.15.2
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
configobj  5.1.0.dev0
pyparsing 2.4.7
mutagen 1.45.1
chromaprint  1.5.1-1

I update my Arch desktop weekly.

**Comment by corubba** [comment] 2022-02-10 18:00
Just judging from the traceback, this looks very much like a duplicate of #662. Could you please see if this still happens with the current master?

**Comment by sandrotosi** [comment] 2022-02-27 05:21
closing as duplicate of #662, please reopen if it's a different issue/not fixed

**Closed by sandrotosi** 2022-02-27 05:21 UTC
Labels: more-information
