### ISSUE TITLE
PyParsing 3.0.0 breaks Puddletag

### ISSUE THREAD

**Issue by RogueScholar** [puddletag/puddletag#575] opened 2021-01-06 06:41 UTC
Luckily this is an easy one.

## Peanut Butter

- [What's New in PyParsing 3.0.0 -  § 1.3.2 Other discontinued features](https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html#id14)
  > ...
  >
  > - operatorPrecedence synonym for infixNotation - convert to calling infixNotation
  >
  > ...

## Grape Jelly

https://github.com/puddletag/puddletag/blob/66aa1f4726986c4310c6ed77676881abbf49de4c/source/puddlestuff/audio_filter.py#L183

## Delicious Python Sandwich

```diff
--- a/puddletag/source/puddlestuff/audio_filter.py
+++ b/puddletag/source/puddlestuff/audio_filter.py
@@ -180,7 +180,7 @@ bool_exprs = [
 field_expr = Combine('%' + Word(alphanums + '_') + '%')
 tokens = QuotedString('"', unquoteResults=False) \
          | field_expr | Word(alphanums + '_')
-bool_expr = operatorPrecedence(tokens, bool_exprs)
+bool_expr = infixNotation(tokens, bool_exprs)
 bool_expr.enablePackrat()
 
 
```

Alright, definitely not one of my better analogies, but it still ends in: **_Voila!_ Puddletag works again!** This change was introduced in July 2013 with PyParsing 2.0.1, so I think you can implement it without any angry users on legacy environments. I did a quick test against v2.3.1 (c. 2018) from PyPI and can confirm it's copasetic at least as far back as that release running Python 3.9.1.

**Comment by sandrotosi** [comment] 2021-01-08 03:50
pyparsing 3.0.0 is still in beta phase, so i dont believe there's a high urgency to get this fixed; would you like to submit a PR for this?

PS: next time, please keep the description strictly technical: describe what the issue is, what the actual outcome expected is, how you intend to address it. Even if the current text may be considered funny, it's distracting from the actual problem. less time "decoding" what's written and sticking to tech details would make it more useful.

**Comment by corubba** [comment] 2022-02-09 23:28
Duplicate of #643

**Closed** 2022-02-10 03:53 UTC
