### ISSUE TITLE
Crash when updating read only file

### ISSUE THREAD

**Issue by poelzi** [puddletag/puddletag#628] opened 2021-09-22 09:20 UTC
I got this crash when updating a file with read only permissions:

```
puddletag Version: 2.0.1
Locale: en_US
Traceback (most recent call last):
  File "/nix/store/02k835rmjyngwy4hn79pc4w1r2341qmv-python3.8-mutagen-1.45.1/lib/python3.8/site-packages/mutagen/_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
PermissionError: [Errno 13] Permission denied: '/tmp/unp/XXX/08. XXX.flac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 807, in writeOneToMany
    s(self)
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddleobjects.py", line 881, in s
    errors = next(f)
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/util.py", line 319, in write
    audio.save()
  File "/nix/store/l98mra9a21lkcr17kjkcdqzsr5nyqp9r-puddletag-2.0.1/lib/python3.8/site-packages/puddlestuff/audioinfo/vorbis.py", line 225, in save
    audio.save()
  File "/nix/store/02k835rmjyngwy4hn79pc4w1r2341qmv-python3.8-mutagen-1.45.1/lib/python3.8/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/02k835rmjyngwy4hn79pc4w1r2341qmv-python3.8-mutagen-1.45.1/lib/python3.8/site-packages/mutagen/_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "/nix/store/zv167zw7gwr9h0gpkfcikdfqnscrd0q6-python3-3.8.9/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/nix/store/02k835rmjyngwy4hn79pc4w1r2341qmv-python3.8-mutagen-1.45.1/lib/python3.8/site-packages/mutagen/_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 13] Permission denied: '/tmp/unp/XXX/08. XXX.flac'
fish: Job 1, '~/.nix-profile/bin/puddletag .' terminated by signal SIGABRT (Abort)
```

**Comment by blueblots** [comment] 2021-09-22 15:24
There will be a fix for this in #547, this issue is also a duplicate of #546.

**Closed** 2021-09-22 16:16 UTC
